### ISSUE TITLE
NullReferenceException, Missing "Modified mGBA executable"

### ISSUE THREAD

**Issue by greigs** [0x0ade/MidiToBGB#1]
Main issue is the latest release crashes for me on launch (windows 10), log below.
Second issue is the release notes state the following, but these files seem to be missing (?) 

```
Note:
It ships with a devbuild of mGBA 0.7, split into multiple libraries, with the following changes:

SDL platform's "executable" built as libmgba-sdl.dll instead of mgba-sdl.exe
Entry point (function main) renamed to mSDLMain
```

Log message:

```
MidiToMGBA 1.1.0.0
No --midi ID given, connecting to last connected device.
#0: loopMIDIPort
Setting up mGBA link
Fatal Error!
System.NullReferenceException: Object reference not set to an instance of an object.
   at MonoMod.RuntimeDetour.DetourNativeX86Platform.Copy(IntPtr src, IntPtr dst, Int32 size) in D:\Repos\MidiToBGB\MonoMod\MonoMod.RuntimeDetour\DetourNativePlatforms.cs:line 71
   at MonoMod.RuntimeDetour.NativeDetour..ctor(MethodBase method, IntPtr from, IntPtr to) in D:\Repos\MidiToBGB\MonoMod\MonoMod.RuntimeDetour\NativeDetour.cs:line 59
   at MidiToMGBA.MGBALink..ctor() in D:\Repos\MidiToBGB\src\MGBALink.cs:line 39
   at MidiToMGBA.Program.Main(String[] args) in D:\Repos\MidiToBGB\src\Program.cs:line 98
```

**Comment by 0x0ade** [comment]
I sadly can't replicate that locally. After downloading the latest release from [https://github.com/0x0ade/MidiToMGBA/releases/download/v1.1.0/Release.zip](https://github.com/0x0ade/MidiToMGBA/releases/download/v1.1.0/Release.zip), all files are present and MidiToMGBA starts up properly.

Can you please share a list of all files after extracting the .zip locally? I'm wondering which files in particular are missing.

**Comment by greigs** [comment]
Zip contents below. Confirmed 49 files after extracting. error.txt created on running. The only .exe is MidiToMGBA.exe, is this correct?. I also tried running it again in a clean folder. Same error. Made sure windows defender realtime protection was off in case that was it.

```
Type = zip
Physical Size = 8177741

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2018-04-26 19:09:22 ....A        74400        32407  libbz2-1.dll
2018-04-26 19:09:22 ....A      1568976       388448  libepoxy-0.dll
2018-04-26 19:09:22 ....A       219464        81458  libexpat-1.dll
2018-04-26 19:09:22 ....A        34176        15353  libffi-6.dll
2018-04-26 19:09:22 ....A       289868       134666  libfontconfig-1.dll
2018-04-26 19:09:23 ....A       685343       352010  libfreetype-6.dll
2018-04-26 19:09:23 ....A       129950        37594  libfribidi-0.dll
2018-04-26 19:09:23 ....A        83150        34498  libgcc_s_seh-1.dll
2018-04-26 19:09:23 ....A      1143569       451132  libglib-2.0-0.dll
2018-04-26 19:09:23 ....A       509691       257945  libgmp-10.dll
2018-04-26 19:09:23 ....A      1333999       567232  libgnutls-30.dll
2018-04-26 19:09:23 ....A       163012        71612  libgomp-1.dll
2018-04-26 19:09:23 ....A       235198       115128  libgraphite2.dll
2018-04-26 19:09:23 ....A       688501       302413  libharfbuzz-0.dll
2018-04-26 19:09:23 ....A       210274       139029  libhogweed-4.dll
2018-04-26 19:09:23 ....A       153221        74402  libidn2-0.dll
2018-04-26 19:09:23 ....A       374970       171186  liblcms2-2.dll
2018-04-26 19:09:23 ....A        66589        29756  liblqr-1-0.dll
2018-04-26 19:09:23 ....A        73639        34851  libltdl-7.dll
2018-04-26 19:09:23 ....A       153325        76528  liblzma-5.dll
2018-04-26 19:09:22 ....A      2045922       857003  libMagickCore-7.Q16HDRI-5.dll
2018-04-26 19:09:22 ....A      1120502       358054  libMagickWand-7.Q16HDRI-5.dll
2018-04-26 19:09:23 ....A       387942       103313  libmgba-sdl.dll
2018-04-26 19:09:23 ....A      1374720       456954  libmgba.dll
2018-04-26 19:09:23 ....A       237131       110699  libnettle-6.dll
2018-04-26 19:09:23 ....A      1008289       245229  libp11-kit-0.dll
2018-04-26 19:09:23 ....A       286369        96868  libpcre-1.dll
2018-04-26 19:09:23 ....A       301729       109577  libpcre2-16-0.dll
2018-04-26 19:09:23 ....A       231566       114745  libpng16-16.dll
2018-04-26 19:09:23 ....A        29601        12519  libraqm-0.dll
2018-04-26 19:09:23 ....A      1691483       574502  libsqlite3-0.dll
2018-04-26 19:09:23 ....A       101599        49478  libtasn1-6.dll
2018-04-26 19:09:23 ....A        57379        24033  libwinpthread-1.dll
2018-04-26 19:09:23 ....A      1311533       585203  libxml2-2.dll
2018-04-26 19:09:23 ....A       112686        49438  libzip.dll
2018-04-26 19:09:22 ....A        65536        13420  mGB.gb
2018-04-27 17:46:55 ....A         1010          433  MidiToMGBA.bat
2018-04-27 18:28:07 ....A        27136        11852  MidiToMGBA.exe
2018-04-27 18:28:07 ....A        36352         8150  MidiToMGBA.pdb
2018-03-19 09:13:06 ....A       337920       142957  Mono.Cecil.dll
2018-04-27 18:27:51 ....A        56320        24444  MonoMod.RuntimeDetour.dll
2018-04-27 18:27:51 ....A       157184        35071  MonoMod.RuntimeDetour.pdb
2018-04-25 21:49:55 ....A        47104        20888  MonoMod.Utils.dll
2018-04-25 21:49:55 ....A        93696        24134  MonoMod.Utils.pdb
2018-02-21 19:30:52 ....A       180224        65787  Sanford.Multimedia.Midi.dll
2018-02-21 19:30:52 ....A       566784       121707  Sanford.Multimedia.Midi.pdb
2018-02-21 19:30:52 ....A       219466        21158  Sanford.Multimedia.Midi.xml
2018-04-26 19:09:22 ....A      1334272       495800  SDL2.dll
2018-04-26 19:09:23 ....A       138240        69595  zlib1.dll
------------------- ----- ------------ ------------  ------------------------
2018-04-27 18:28:07           21751010      8170659  49 files
```

**Comment by 0x0ade** [comment]
All required files do exist, but it seems like some symbols in the .dlls (or the .dlls in general) aren't resolved properly.

Are you running on a 32-bit or 64-bit operating system?

**Comment by greigs** [comment]
64 bit, windows 10

**Comment by greigs** [comment]
Any luck with this? I'd still like to use it!
